title: MVeers's Page
author: Josue Cadneas
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I"m just regular college student

# social links
github_username: MVeers

show_excerpts: true # set to false to remove excerpts on the homepage

theme:minima
